from enum import StrEnum


class AccessState(StrEnum):
    PUBLIC = "public"
    PUBLIC_METADATA_ONLY = "public_metadata_only"
    LOGIN_REQUIRED = "login_required"
    REGISTRATION_REQUIRED = "registration_required"
    PROSPECTIVE_BIDDER_REQUIRED = "prospective_bidder_required"
    INVITATION_ONLY = "invitation_only"
    SUBSCRIPTION_REQUIRED = "subscription_required"
    PAYMENT_REQUIRED = "payment_required"
    CAPTCHA = "captcha"
    CAPTCHA_REQUIRED = "captcha_required"
    VENDOR_PROFILE_REQUIRED = "vendor_profile_required"
    RESPONSE_SYSTEM_EXTERNAL = "response_system_external"
    EXTERNAL_RESPONSE_SYSTEM = "external_response_system"
    MIGRATED = "migrated"
    RESTRICTED = "restricted"
    UNAVAILABLE = "unavailable"
    NOT_FOUND = "not_found"
    MALFORMED = "malformed"
    UNSUPPORTED = "unsupported"
    TRANSIENT_ERROR = "transient_error"
    REMOVED = "removed"
    UNKNOWN = "unknown"


class DocumentEligibility(StrEnum):
    INCLUDE = "include"
    EXCLUDE = "exclude"
    REVIEW = "review"
    RESTRICTED = "restricted"


class DocumentRole(StrEnum):
    SOLICITATION = "solicitation"
    RFP = "rfp"
    RFQ = "rfq"
    RFI = "rfi"
    IFB = "ifb"
    ITB = "itb"
    INVITATION_TO_BID = "invitation_to_bid"
    REQUEST_FOR_QUALIFICATIONS = "request_for_qualifications"
    SOW = "sow"
    PWS = "pws"
    SPECIFICATION = "specification"
    STATEMENT_OF_OBJECTIVES = "statement_of_objectives"
    SCOPE = "scope"
    PRICING_SHEET = "pricing_sheet"
    BID_FORM = "bid_form"
    RESPONSE_TEMPLATE = "response_template"
    TERMS_AND_CONDITIONS = "terms_and_conditions"
    EXHIBIT = "exhibit"
    APPENDIX = "appendix"
    ATTACHMENT = "attachment"
    DRAWING = "drawing"
    PLAN = "plan"
    ADDENDUM = "addendum"
    AMENDMENT = "amendment"
    QUESTIONS_AND_ANSWERS = "questions_and_answers"
    PRICING = "pricing"
    PRE_BID_MATERIAL = "pre_bid_material"
    ATTENDEE_LIST = "attendee_list"
    NOTICE = "notice"
    AWARD_NOTICE = "award_notice"
    INTENT_TO_AWARD = "intent_to_award"
    BID_TABULATION = "bid_tabulation"
    CONTRACT = "contract"
    CANCELLATION_NOTICE = "cancellation_notice"
    EVALUATION = "evaluation"
    SUBMISSION_INSTRUCTIONS = "submission_instructions"
    REQUIRED_FORM = "required_form"
    OTHER = "other"
    UNKNOWN = "unknown"


class DocumentRelationship(StrEnum):
    PRIMARY = "primary"
    SUPPLEMENT = "supplement"
    ADDENDUM_TO = "addendum_to"
    AMENDMENT_TO = "amendment_to"
    REPLACES = "replaces"
    SUPERSEDES = "supersedes"
    QUESTIONS_FOR = "questions_for"
    AWARD_FOR = "award_for"
    CANCELLATION_FOR = "cancellation_for"
    ATTACHMENT_TO = "attachment_to"
    EXHIBIT_TO = "exhibit_to"
    PRICING_FOR = "pricing_for"
    RESPONSE_TEMPLATE_FOR = "response_template_for"
    RELATED = "related"


class RetrievalState(StrEnum):
    DISCOVERED = "discovered"
    INELIGIBLE = "ineligible"
    ELIGIBLE = "eligible"
    QUEUED = "queued"
    LEASED = "leased"
    DOWNLOADING = "downloading"
    DOWNLOADED = "downloaded"
    UNCHANGED = "unchanged"
    SUPERSEDED = "superseded"
    RESTRICTED = "restricted"
    LOGIN_REQUIRED = "login_required"
    REGISTRATION_REQUIRED = "registration_required"
    CAPTCHA = "captcha"
    NOT_FOUND = "not_found"
    FAILED = "failed"
    QUARANTINED = "quarantined"
    CANCELED = "canceled"


class OpportunityStatus(StrEnum):
    FORECAST = "forecast"
    OPEN = "open"
    CLOSED = "closed"
    AWARDED = "awarded"
    CANCELLED = "cancelled"
    UNKNOWN = "unknown"
